# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Wy56hGCFX0B4PMP6cnYo_FjsFV_B085
"""

import pandas as pd
data = {
    'Ism': ['Ali', 'Gulbahor', 'Jasur', 'Nilufar'],
    'Yosh': [25, 30, 22, 28],
    'Kasb': ['O‘qituvchi', 'Shifokor', 'Dasturchi', 'Muhandis']
}

df = pd.DataFrame(data)

print(df)